language: node_js

node_js:
- 'node'
- 'lts/carbon'
- 'lts/boron'
- 'lts/argon'

before_install:
  - npm install -g greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

after_script:
  - greenkeeper-lockfile-upload

env:
  secure: E9HwRWHEs5q9jxd2pKehuSmbFlR7JpDqcmR6fwSHxCTHFVPTiHhaKdXCvjUQx+hFnzMq3BleX6IOuDn9V2cavhZlt9OpkDQDcDTvKpIIenAH/lgBUrDflqpEJ+Z91e1SWcCwcDbNMWp+JUEIWqrZsmuIZsRj9FoLt4ucHu8jvfzek7i1erd2iUW4k7Wl+kuytclZdzpgajVgQNYTMI7gueV/1ZV+wdpCWcW7ydQRYJJRtPB1bs32z6joXvQshz5q6LKrNk1BJ8wX0/dNWtrVNBSzxzwwhlIWvxnMYhzXRwN2McARkRnNcH/ry9gExeCe3GGgRpcHspXPepZEzQ99gK9VOS4JUTcBdlVNBZ5W6iLvJp++9jZ7N18I5z6242EsbB9HXoXbcFWjm20X4Aom1rZf42zMSQOlSuuRpjdJy1LXPYYB/UTQk4x+BarP5ig+YotoI/KhbTUFfFCizlemPJJgov2uJBFXJ3V9jZNVOEGkyJ1+xeW4UG8CcB7G6XPbIj5FxYUWU4gOhRZw555meYW/Bsy9U1aW1luhsEbGLHXLvtyMdnFOJ/DNwHNW0hZoiZdZ70MPuf2ynyEVOwlAtt6BQ7AVVPMgppNM7fAIdEtOE3lTJ2o88qlI6d50qXnABxmLTzxLlFwysSCSm21m9YQU5TPvvu1RwxsLCfopO3A=
